package com.yuyuedao.yydwechat.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ATokenExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table a_token
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table a_token
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table a_token
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    public ATokenExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table a_token
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSidIsNull() {
            addCriterion("sid is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("sid is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(Integer value) {
            addCriterion("sid =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(Integer value) {
            addCriterion("sid <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(Integer value) {
            addCriterion("sid >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sid >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(Integer value) {
            addCriterion("sid <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(Integer value) {
            addCriterion("sid <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<Integer> values) {
            addCriterion("sid in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<Integer> values) {
            addCriterion("sid not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(Integer value1, Integer value2) {
            addCriterion("sid between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(Integer value1, Integer value2) {
            addCriterion("sid not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andAppidIsNull() {
            addCriterion("appid is null");
            return (Criteria) this;
        }

        public Criteria andAppidIsNotNull() {
            addCriterion("appid is not null");
            return (Criteria) this;
        }

        public Criteria andAppidEqualTo(String value) {
            addCriterion("appid =", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotEqualTo(String value) {
            addCriterion("appid <>", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThan(String value) {
            addCriterion("appid >", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThanOrEqualTo(String value) {
            addCriterion("appid >=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThan(String value) {
            addCriterion("appid <", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThanOrEqualTo(String value) {
            addCriterion("appid <=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLike(String value) {
            addCriterion("appid like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotLike(String value) {
            addCriterion("appid not like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidIn(List<String> values) {
            addCriterion("appid in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotIn(List<String> values) {
            addCriterion("appid not in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidBetween(String value1, String value2) {
            addCriterion("appid between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotBetween(String value1, String value2) {
            addCriterion("appid not between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppsecretIsNull() {
            addCriterion("appsecret is null");
            return (Criteria) this;
        }

        public Criteria andAppsecretIsNotNull() {
            addCriterion("appsecret is not null");
            return (Criteria) this;
        }

        public Criteria andAppsecretEqualTo(String value) {
            addCriterion("appsecret =", value, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAppsecretNotEqualTo(String value) {
            addCriterion("appsecret <>", value, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAppsecretGreaterThan(String value) {
            addCriterion("appsecret >", value, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAppsecretGreaterThanOrEqualTo(String value) {
            addCriterion("appsecret >=", value, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAppsecretLessThan(String value) {
            addCriterion("appsecret <", value, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAppsecretLessThanOrEqualTo(String value) {
            addCriterion("appsecret <=", value, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAppsecretLike(String value) {
            addCriterion("appsecret like", value, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAppsecretNotLike(String value) {
            addCriterion("appsecret not like", value, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAppsecretIn(List<String> values) {
            addCriterion("appsecret in", values, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAppsecretNotIn(List<String> values) {
            addCriterion("appsecret not in", values, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAppsecretBetween(String value1, String value2) {
            addCriterion("appsecret between", value1, value2, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAppsecretNotBetween(String value1, String value2) {
            addCriterion("appsecret not between", value1, value2, "appsecret");
            return (Criteria) this;
        }

        public Criteria andAuthTokenIsNull() {
            addCriterion("auth_token is null");
            return (Criteria) this;
        }

        public Criteria andAuthTokenIsNotNull() {
            addCriterion("auth_token is not null");
            return (Criteria) this;
        }

        public Criteria andAuthTokenEqualTo(String value) {
            addCriterion("auth_token =", value, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenNotEqualTo(String value) {
            addCriterion("auth_token <>", value, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenGreaterThan(String value) {
            addCriterion("auth_token >", value, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenGreaterThanOrEqualTo(String value) {
            addCriterion("auth_token >=", value, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenLessThan(String value) {
            addCriterion("auth_token <", value, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenLessThanOrEqualTo(String value) {
            addCriterion("auth_token <=", value, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenLike(String value) {
            addCriterion("auth_token like", value, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenNotLike(String value) {
            addCriterion("auth_token not like", value, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenIn(List<String> values) {
            addCriterion("auth_token in", values, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenNotIn(List<String> values) {
            addCriterion("auth_token not in", values, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenBetween(String value1, String value2) {
            addCriterion("auth_token between", value1, value2, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenNotBetween(String value1, String value2) {
            addCriterion("auth_token not between", value1, value2, "authToken");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeIsNull() {
            addCriterion("auth_token_time is null");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeIsNotNull() {
            addCriterion("auth_token_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeEqualTo(Date value) {
            addCriterion("auth_token_time =", value, "authTokenTime");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeNotEqualTo(Date value) {
            addCriterion("auth_token_time <>", value, "authTokenTime");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeGreaterThan(Date value) {
            addCriterion("auth_token_time >", value, "authTokenTime");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("auth_token_time >=", value, "authTokenTime");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeLessThan(Date value) {
            addCriterion("auth_token_time <", value, "authTokenTime");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeLessThanOrEqualTo(Date value) {
            addCriterion("auth_token_time <=", value, "authTokenTime");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeIn(List<Date> values) {
            addCriterion("auth_token_time in", values, "authTokenTime");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeNotIn(List<Date> values) {
            addCriterion("auth_token_time not in", values, "authTokenTime");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeBetween(Date value1, Date value2) {
            addCriterion("auth_token_time between", value1, value2, "authTokenTime");
            return (Criteria) this;
        }

        public Criteria andAuthTokenTimeNotBetween(Date value1, Date value2) {
            addCriterion("auth_token_time not between", value1, value2, "authTokenTime");
            return (Criteria) this;
        }

        public Criteria andJsticketIsNull() {
            addCriterion("jsticket is null");
            return (Criteria) this;
        }

        public Criteria andJsticketIsNotNull() {
            addCriterion("jsticket is not null");
            return (Criteria) this;
        }

        public Criteria andJsticketEqualTo(String value) {
            addCriterion("jsticket =", value, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketNotEqualTo(String value) {
            addCriterion("jsticket <>", value, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketGreaterThan(String value) {
            addCriterion("jsticket >", value, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketGreaterThanOrEqualTo(String value) {
            addCriterion("jsticket >=", value, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketLessThan(String value) {
            addCriterion("jsticket <", value, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketLessThanOrEqualTo(String value) {
            addCriterion("jsticket <=", value, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketLike(String value) {
            addCriterion("jsticket like", value, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketNotLike(String value) {
            addCriterion("jsticket not like", value, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketIn(List<String> values) {
            addCriterion("jsticket in", values, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketNotIn(List<String> values) {
            addCriterion("jsticket not in", values, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketBetween(String value1, String value2) {
            addCriterion("jsticket between", value1, value2, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketNotBetween(String value1, String value2) {
            addCriterion("jsticket not between", value1, value2, "jsticket");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeIsNull() {
            addCriterion("jsticket_time is null");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeIsNotNull() {
            addCriterion("jsticket_time is not null");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeEqualTo(Date value) {
            addCriterion("jsticket_time =", value, "jsticketTime");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeNotEqualTo(Date value) {
            addCriterion("jsticket_time <>", value, "jsticketTime");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeGreaterThan(Date value) {
            addCriterion("jsticket_time >", value, "jsticketTime");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("jsticket_time >=", value, "jsticketTime");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeLessThan(Date value) {
            addCriterion("jsticket_time <", value, "jsticketTime");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeLessThanOrEqualTo(Date value) {
            addCriterion("jsticket_time <=", value, "jsticketTime");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeIn(List<Date> values) {
            addCriterion("jsticket_time in", values, "jsticketTime");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeNotIn(List<Date> values) {
            addCriterion("jsticket_time not in", values, "jsticketTime");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeBetween(Date value1, Date value2) {
            addCriterion("jsticket_time between", value1, value2, "jsticketTime");
            return (Criteria) this;
        }

        public Criteria andJsticketTimeNotBetween(Date value1, Date value2) {
            addCriterion("jsticket_time not between", value1, value2, "jsticketTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table a_token
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table a_token
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}