package com.yuyuedao.yydwechat.entity;

import java.util.Date;

public class AToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_token.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_token.appid
     *
     * @mbg.generated
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_token.appsecret
     *
     * @mbg.generated
     */
    private String appsecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_token.auth_token
     *
     * @mbg.generated
     */
    private String authToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_token.auth_token_time
     *
     * @mbg.generated
     */
    private Date authTokenTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_token.jsticket
     *
     * @mbg.generated
     */
    private String jsticket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_token.jsticket_time
     *
     * @mbg.generated
     */
    private Date jsticketTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_token.sid
     *
     * @return the value of a_token.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_token.sid
     *
     * @param sid the value for a_token.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_token.appid
     *
     * @return the value of a_token.appid
     *
     * @mbg.generated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_token.appid
     *
     * @param appid the value for a_token.appid
     *
     * @mbg.generated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_token.appsecret
     *
     * @return the value of a_token.appsecret
     *
     * @mbg.generated
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_token.appsecret
     *
     * @param appsecret the value for a_token.appsecret
     *
     * @mbg.generated
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_token.auth_token
     *
     * @return the value of a_token.auth_token
     *
     * @mbg.generated
     */
    public String getAuthToken() {
        return authToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_token.auth_token
     *
     * @param authToken the value for a_token.auth_token
     *
     * @mbg.generated
     */
    public void setAuthToken(String authToken) {
        this.authToken = authToken == null ? null : authToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_token.auth_token_time
     *
     * @return the value of a_token.auth_token_time
     *
     * @mbg.generated
     */
    public Date getAuthTokenTime() {
        return authTokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_token.auth_token_time
     *
     * @param authTokenTime the value for a_token.auth_token_time
     *
     * @mbg.generated
     */
    public void setAuthTokenTime(Date authTokenTime) {
        this.authTokenTime = authTokenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_token.jsticket
     *
     * @return the value of a_token.jsticket
     *
     * @mbg.generated
     */
    public String getJsticket() {
        return jsticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_token.jsticket
     *
     * @param jsticket the value for a_token.jsticket
     *
     * @mbg.generated
     */
    public void setJsticket(String jsticket) {
        this.jsticket = jsticket == null ? null : jsticket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_token.jsticket_time
     *
     * @return the value of a_token.jsticket_time
     *
     * @mbg.generated
     */
    public Date getJsticketTime() {
        return jsticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_token.jsticket_time
     *
     * @param jsticketTime the value for a_token.jsticket_time
     *
     * @mbg.generated
     */
    public void setJsticketTime(Date jsticketTime) {
        this.jsticketTime = jsticketTime;
    }
}