package com.yuyuedao.yydwechat.entity;

public class DrawWinning {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_winning.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_winning.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_winning.prize
     *
     * @mbg.generated
     */
    private String prize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_winning.activityid
     *
     * @mbg.generated
     */
    private Integer activityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_winning.activityname
     *
     * @mbg.generated
     */
    private String activityname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_winning.sid
     *
     * @return the value of draw_winning.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_winning.sid
     *
     * @param sid the value for draw_winning.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_winning.openid
     *
     * @return the value of draw_winning.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_winning.openid
     *
     * @param openid the value for draw_winning.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_winning.prize
     *
     * @return the value of draw_winning.prize
     *
     * @mbg.generated
     */
    public String getPrize() {
        return prize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_winning.prize
     *
     * @param prize the value for draw_winning.prize
     *
     * @mbg.generated
     */
    public void setPrize(String prize) {
        this.prize = prize == null ? null : prize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_winning.activityid
     *
     * @return the value of draw_winning.activityid
     *
     * @mbg.generated
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_winning.activityid
     *
     * @param activityid the value for draw_winning.activityid
     *
     * @mbg.generated
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_winning.activityname
     *
     * @return the value of draw_winning.activityname
     *
     * @mbg.generated
     */
    public String getActivityname() {
        return activityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_winning.activityname
     *
     * @param activityname the value for draw_winning.activityname
     *
     * @mbg.generated
     */
    public void setActivityname(String activityname) {
        this.activityname = activityname == null ? null : activityname.trim();
    }
}