package com.yuyuedao.yydwechat.entity;

import java.util.Date;

public class DrawActivity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.lotterytime
     *
     * @mbg.generated
     */
    private Date lotterytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.picurl
     *
     * @mbg.generated
     */
    private String picurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.appurl
     *
     * @mbg.generated
     */
    private String appurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.textmsg
     *
     * @mbg.generated
     */
    private String textmsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.sponsoric
     *
     * @mbg.generated
     */
    private String sponsoric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.advertisepic
     *
     * @mbg.generated
     */
    private String advertisepic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.advertiseurl
     *
     * @mbg.generated
     */
    private String advertiseurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.quota_all
     *
     * @mbg.generated
     */
    private Integer quotaAll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.quota_one
     *
     * @mbg.generated
     */
    private Integer quotaOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.quota_two
     *
     * @mbg.generated
     */
    private Integer quotaTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column draw_activity.quota_three
     *
     * @mbg.generated
     */
    private Integer quotaThree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.sid
     *
     * @return the value of draw_activity.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.sid
     *
     * @param sid the value for draw_activity.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.sname
     *
     * @return the value of draw_activity.sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.sname
     *
     * @param sname the value for draw_activity.sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.lotterytime
     *
     * @return the value of draw_activity.lotterytime
     *
     * @mbg.generated
     */
    public Date getLotterytime() {
        return lotterytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.lotterytime
     *
     * @param lotterytime the value for draw_activity.lotterytime
     *
     * @mbg.generated
     */
    public void setLotterytime(Date lotterytime) {
        this.lotterytime = lotterytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.picurl
     *
     * @return the value of draw_activity.picurl
     *
     * @mbg.generated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.picurl
     *
     * @param picurl the value for draw_activity.picurl
     *
     * @mbg.generated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.appurl
     *
     * @return the value of draw_activity.appurl
     *
     * @mbg.generated
     */
    public String getAppurl() {
        return appurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.appurl
     *
     * @param appurl the value for draw_activity.appurl
     *
     * @mbg.generated
     */
    public void setAppurl(String appurl) {
        this.appurl = appurl == null ? null : appurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.textmsg
     *
     * @return the value of draw_activity.textmsg
     *
     * @mbg.generated
     */
    public String getTextmsg() {
        return textmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.textmsg
     *
     * @param textmsg the value for draw_activity.textmsg
     *
     * @mbg.generated
     */
    public void setTextmsg(String textmsg) {
        this.textmsg = textmsg == null ? null : textmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.sponsoric
     *
     * @return the value of draw_activity.sponsoric
     *
     * @mbg.generated
     */
    public String getSponsoric() {
        return sponsoric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.sponsoric
     *
     * @param sponsoric the value for draw_activity.sponsoric
     *
     * @mbg.generated
     */
    public void setSponsoric(String sponsoric) {
        this.sponsoric = sponsoric == null ? null : sponsoric.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.advertisepic
     *
     * @return the value of draw_activity.advertisepic
     *
     * @mbg.generated
     */
    public String getAdvertisepic() {
        return advertisepic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.advertisepic
     *
     * @param advertisepic the value for draw_activity.advertisepic
     *
     * @mbg.generated
     */
    public void setAdvertisepic(String advertisepic) {
        this.advertisepic = advertisepic == null ? null : advertisepic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.advertiseurl
     *
     * @return the value of draw_activity.advertiseurl
     *
     * @mbg.generated
     */
    public String getAdvertiseurl() {
        return advertiseurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.advertiseurl
     *
     * @param advertiseurl the value for draw_activity.advertiseurl
     *
     * @mbg.generated
     */
    public void setAdvertiseurl(String advertiseurl) {
        this.advertiseurl = advertiseurl == null ? null : advertiseurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.quota_all
     *
     * @return the value of draw_activity.quota_all
     *
     * @mbg.generated
     */
    public Integer getQuotaAll() {
        return quotaAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.quota_all
     *
     * @param quotaAll the value for draw_activity.quota_all
     *
     * @mbg.generated
     */
    public void setQuotaAll(Integer quotaAll) {
        this.quotaAll = quotaAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.quota_one
     *
     * @return the value of draw_activity.quota_one
     *
     * @mbg.generated
     */
    public Integer getQuotaOne() {
        return quotaOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.quota_one
     *
     * @param quotaOne the value for draw_activity.quota_one
     *
     * @mbg.generated
     */
    public void setQuotaOne(Integer quotaOne) {
        this.quotaOne = quotaOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.quota_two
     *
     * @return the value of draw_activity.quota_two
     *
     * @mbg.generated
     */
    public Integer getQuotaTwo() {
        return quotaTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.quota_two
     *
     * @param quotaTwo the value for draw_activity.quota_two
     *
     * @mbg.generated
     */
    public void setQuotaTwo(Integer quotaTwo) {
        this.quotaTwo = quotaTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column draw_activity.quota_three
     *
     * @return the value of draw_activity.quota_three
     *
     * @mbg.generated
     */
    public Integer getQuotaThree() {
        return quotaThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column draw_activity.quota_three
     *
     * @param quotaThree the value for draw_activity.quota_three
     *
     * @mbg.generated
     */
    public void setQuotaThree(Integer quotaThree) {
        this.quotaThree = quotaThree;
    }
}