package com.yuyuedao.yydwechat.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DrawActivityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    public DrawActivityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSidIsNull() {
            addCriterion("sid is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("sid is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(Integer value) {
            addCriterion("sid =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(Integer value) {
            addCriterion("sid <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(Integer value) {
            addCriterion("sid >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sid >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(Integer value) {
            addCriterion("sid <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(Integer value) {
            addCriterion("sid <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<Integer> values) {
            addCriterion("sid in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<Integer> values) {
            addCriterion("sid not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(Integer value1, Integer value2) {
            addCriterion("sid between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(Integer value1, Integer value2) {
            addCriterion("sid not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSnameIsNull() {
            addCriterion("sname is null");
            return (Criteria) this;
        }

        public Criteria andSnameIsNotNull() {
            addCriterion("sname is not null");
            return (Criteria) this;
        }

        public Criteria andSnameEqualTo(String value) {
            addCriterion("sname =", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotEqualTo(String value) {
            addCriterion("sname <>", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameGreaterThan(String value) {
            addCriterion("sname >", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameGreaterThanOrEqualTo(String value) {
            addCriterion("sname >=", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLessThan(String value) {
            addCriterion("sname <", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLessThanOrEqualTo(String value) {
            addCriterion("sname <=", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameLike(String value) {
            addCriterion("sname like", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotLike(String value) {
            addCriterion("sname not like", value, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameIn(List<String> values) {
            addCriterion("sname in", values, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotIn(List<String> values) {
            addCriterion("sname not in", values, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameBetween(String value1, String value2) {
            addCriterion("sname between", value1, value2, "sname");
            return (Criteria) this;
        }

        public Criteria andSnameNotBetween(String value1, String value2) {
            addCriterion("sname not between", value1, value2, "sname");
            return (Criteria) this;
        }

        public Criteria andLotterytimeIsNull() {
            addCriterion("lotterytime is null");
            return (Criteria) this;
        }

        public Criteria andLotterytimeIsNotNull() {
            addCriterion("lotterytime is not null");
            return (Criteria) this;
        }

        public Criteria andLotterytimeEqualTo(Date value) {
            addCriterion("lotterytime =", value, "lotterytime");
            return (Criteria) this;
        }

        public Criteria andLotterytimeNotEqualTo(Date value) {
            addCriterion("lotterytime <>", value, "lotterytime");
            return (Criteria) this;
        }

        public Criteria andLotterytimeGreaterThan(Date value) {
            addCriterion("lotterytime >", value, "lotterytime");
            return (Criteria) this;
        }

        public Criteria andLotterytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lotterytime >=", value, "lotterytime");
            return (Criteria) this;
        }

        public Criteria andLotterytimeLessThan(Date value) {
            addCriterion("lotterytime <", value, "lotterytime");
            return (Criteria) this;
        }

        public Criteria andLotterytimeLessThanOrEqualTo(Date value) {
            addCriterion("lotterytime <=", value, "lotterytime");
            return (Criteria) this;
        }

        public Criteria andLotterytimeIn(List<Date> values) {
            addCriterion("lotterytime in", values, "lotterytime");
            return (Criteria) this;
        }

        public Criteria andLotterytimeNotIn(List<Date> values) {
            addCriterion("lotterytime not in", values, "lotterytime");
            return (Criteria) this;
        }

        public Criteria andLotterytimeBetween(Date value1, Date value2) {
            addCriterion("lotterytime between", value1, value2, "lotterytime");
            return (Criteria) this;
        }

        public Criteria andLotterytimeNotBetween(Date value1, Date value2) {
            addCriterion("lotterytime not between", value1, value2, "lotterytime");
            return (Criteria) this;
        }

        public Criteria andPicurlIsNull() {
            addCriterion("picurl is null");
            return (Criteria) this;
        }

        public Criteria andPicurlIsNotNull() {
            addCriterion("picurl is not null");
            return (Criteria) this;
        }

        public Criteria andPicurlEqualTo(String value) {
            addCriterion("picurl =", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotEqualTo(String value) {
            addCriterion("picurl <>", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlGreaterThan(String value) {
            addCriterion("picurl >", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlGreaterThanOrEqualTo(String value) {
            addCriterion("picurl >=", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLessThan(String value) {
            addCriterion("picurl <", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLessThanOrEqualTo(String value) {
            addCriterion("picurl <=", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLike(String value) {
            addCriterion("picurl like", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotLike(String value) {
            addCriterion("picurl not like", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlIn(List<String> values) {
            addCriterion("picurl in", values, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotIn(List<String> values) {
            addCriterion("picurl not in", values, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlBetween(String value1, String value2) {
            addCriterion("picurl between", value1, value2, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotBetween(String value1, String value2) {
            addCriterion("picurl not between", value1, value2, "picurl");
            return (Criteria) this;
        }

        public Criteria andAppurlIsNull() {
            addCriterion("appurl is null");
            return (Criteria) this;
        }

        public Criteria andAppurlIsNotNull() {
            addCriterion("appurl is not null");
            return (Criteria) this;
        }

        public Criteria andAppurlEqualTo(String value) {
            addCriterion("appurl =", value, "appurl");
            return (Criteria) this;
        }

        public Criteria andAppurlNotEqualTo(String value) {
            addCriterion("appurl <>", value, "appurl");
            return (Criteria) this;
        }

        public Criteria andAppurlGreaterThan(String value) {
            addCriterion("appurl >", value, "appurl");
            return (Criteria) this;
        }

        public Criteria andAppurlGreaterThanOrEqualTo(String value) {
            addCriterion("appurl >=", value, "appurl");
            return (Criteria) this;
        }

        public Criteria andAppurlLessThan(String value) {
            addCriterion("appurl <", value, "appurl");
            return (Criteria) this;
        }

        public Criteria andAppurlLessThanOrEqualTo(String value) {
            addCriterion("appurl <=", value, "appurl");
            return (Criteria) this;
        }

        public Criteria andAppurlLike(String value) {
            addCriterion("appurl like", value, "appurl");
            return (Criteria) this;
        }

        public Criteria andAppurlNotLike(String value) {
            addCriterion("appurl not like", value, "appurl");
            return (Criteria) this;
        }

        public Criteria andAppurlIn(List<String> values) {
            addCriterion("appurl in", values, "appurl");
            return (Criteria) this;
        }

        public Criteria andAppurlNotIn(List<String> values) {
            addCriterion("appurl not in", values, "appurl");
            return (Criteria) this;
        }

        public Criteria andAppurlBetween(String value1, String value2) {
            addCriterion("appurl between", value1, value2, "appurl");
            return (Criteria) this;
        }

        public Criteria andAppurlNotBetween(String value1, String value2) {
            addCriterion("appurl not between", value1, value2, "appurl");
            return (Criteria) this;
        }

        public Criteria andTextmsgIsNull() {
            addCriterion("textmsg is null");
            return (Criteria) this;
        }

        public Criteria andTextmsgIsNotNull() {
            addCriterion("textmsg is not null");
            return (Criteria) this;
        }

        public Criteria andTextmsgEqualTo(String value) {
            addCriterion("textmsg =", value, "textmsg");
            return (Criteria) this;
        }

        public Criteria andTextmsgNotEqualTo(String value) {
            addCriterion("textmsg <>", value, "textmsg");
            return (Criteria) this;
        }

        public Criteria andTextmsgGreaterThan(String value) {
            addCriterion("textmsg >", value, "textmsg");
            return (Criteria) this;
        }

        public Criteria andTextmsgGreaterThanOrEqualTo(String value) {
            addCriterion("textmsg >=", value, "textmsg");
            return (Criteria) this;
        }

        public Criteria andTextmsgLessThan(String value) {
            addCriterion("textmsg <", value, "textmsg");
            return (Criteria) this;
        }

        public Criteria andTextmsgLessThanOrEqualTo(String value) {
            addCriterion("textmsg <=", value, "textmsg");
            return (Criteria) this;
        }

        public Criteria andTextmsgLike(String value) {
            addCriterion("textmsg like", value, "textmsg");
            return (Criteria) this;
        }

        public Criteria andTextmsgNotLike(String value) {
            addCriterion("textmsg not like", value, "textmsg");
            return (Criteria) this;
        }

        public Criteria andTextmsgIn(List<String> values) {
            addCriterion("textmsg in", values, "textmsg");
            return (Criteria) this;
        }

        public Criteria andTextmsgNotIn(List<String> values) {
            addCriterion("textmsg not in", values, "textmsg");
            return (Criteria) this;
        }

        public Criteria andTextmsgBetween(String value1, String value2) {
            addCriterion("textmsg between", value1, value2, "textmsg");
            return (Criteria) this;
        }

        public Criteria andTextmsgNotBetween(String value1, String value2) {
            addCriterion("textmsg not between", value1, value2, "textmsg");
            return (Criteria) this;
        }

        public Criteria andSponsoricIsNull() {
            addCriterion("sponsoric is null");
            return (Criteria) this;
        }

        public Criteria andSponsoricIsNotNull() {
            addCriterion("sponsoric is not null");
            return (Criteria) this;
        }

        public Criteria andSponsoricEqualTo(String value) {
            addCriterion("sponsoric =", value, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andSponsoricNotEqualTo(String value) {
            addCriterion("sponsoric <>", value, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andSponsoricGreaterThan(String value) {
            addCriterion("sponsoric >", value, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andSponsoricGreaterThanOrEqualTo(String value) {
            addCriterion("sponsoric >=", value, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andSponsoricLessThan(String value) {
            addCriterion("sponsoric <", value, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andSponsoricLessThanOrEqualTo(String value) {
            addCriterion("sponsoric <=", value, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andSponsoricLike(String value) {
            addCriterion("sponsoric like", value, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andSponsoricNotLike(String value) {
            addCriterion("sponsoric not like", value, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andSponsoricIn(List<String> values) {
            addCriterion("sponsoric in", values, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andSponsoricNotIn(List<String> values) {
            addCriterion("sponsoric not in", values, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andSponsoricBetween(String value1, String value2) {
            addCriterion("sponsoric between", value1, value2, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andSponsoricNotBetween(String value1, String value2) {
            addCriterion("sponsoric not between", value1, value2, "sponsoric");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicIsNull() {
            addCriterion("advertisepic is null");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicIsNotNull() {
            addCriterion("advertisepic is not null");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicEqualTo(String value) {
            addCriterion("advertisepic =", value, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicNotEqualTo(String value) {
            addCriterion("advertisepic <>", value, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicGreaterThan(String value) {
            addCriterion("advertisepic >", value, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicGreaterThanOrEqualTo(String value) {
            addCriterion("advertisepic >=", value, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicLessThan(String value) {
            addCriterion("advertisepic <", value, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicLessThanOrEqualTo(String value) {
            addCriterion("advertisepic <=", value, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicLike(String value) {
            addCriterion("advertisepic like", value, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicNotLike(String value) {
            addCriterion("advertisepic not like", value, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicIn(List<String> values) {
            addCriterion("advertisepic in", values, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicNotIn(List<String> values) {
            addCriterion("advertisepic not in", values, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicBetween(String value1, String value2) {
            addCriterion("advertisepic between", value1, value2, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertisepicNotBetween(String value1, String value2) {
            addCriterion("advertisepic not between", value1, value2, "advertisepic");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlIsNull() {
            addCriterion("advertiseurl is null");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlIsNotNull() {
            addCriterion("advertiseurl is not null");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlEqualTo(String value) {
            addCriterion("advertiseurl =", value, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlNotEqualTo(String value) {
            addCriterion("advertiseurl <>", value, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlGreaterThan(String value) {
            addCriterion("advertiseurl >", value, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlGreaterThanOrEqualTo(String value) {
            addCriterion("advertiseurl >=", value, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlLessThan(String value) {
            addCriterion("advertiseurl <", value, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlLessThanOrEqualTo(String value) {
            addCriterion("advertiseurl <=", value, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlLike(String value) {
            addCriterion("advertiseurl like", value, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlNotLike(String value) {
            addCriterion("advertiseurl not like", value, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlIn(List<String> values) {
            addCriterion("advertiseurl in", values, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlNotIn(List<String> values) {
            addCriterion("advertiseurl not in", values, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlBetween(String value1, String value2) {
            addCriterion("advertiseurl between", value1, value2, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andAdvertiseurlNotBetween(String value1, String value2) {
            addCriterion("advertiseurl not between", value1, value2, "advertiseurl");
            return (Criteria) this;
        }

        public Criteria andQuotaAllIsNull() {
            addCriterion("quota_all is null");
            return (Criteria) this;
        }

        public Criteria andQuotaAllIsNotNull() {
            addCriterion("quota_all is not null");
            return (Criteria) this;
        }

        public Criteria andQuotaAllEqualTo(Integer value) {
            addCriterion("quota_all =", value, "quotaAll");
            return (Criteria) this;
        }

        public Criteria andQuotaAllNotEqualTo(Integer value) {
            addCriterion("quota_all <>", value, "quotaAll");
            return (Criteria) this;
        }

        public Criteria andQuotaAllGreaterThan(Integer value) {
            addCriterion("quota_all >", value, "quotaAll");
            return (Criteria) this;
        }

        public Criteria andQuotaAllGreaterThanOrEqualTo(Integer value) {
            addCriterion("quota_all >=", value, "quotaAll");
            return (Criteria) this;
        }

        public Criteria andQuotaAllLessThan(Integer value) {
            addCriterion("quota_all <", value, "quotaAll");
            return (Criteria) this;
        }

        public Criteria andQuotaAllLessThanOrEqualTo(Integer value) {
            addCriterion("quota_all <=", value, "quotaAll");
            return (Criteria) this;
        }

        public Criteria andQuotaAllIn(List<Integer> values) {
            addCriterion("quota_all in", values, "quotaAll");
            return (Criteria) this;
        }

        public Criteria andQuotaAllNotIn(List<Integer> values) {
            addCriterion("quota_all not in", values, "quotaAll");
            return (Criteria) this;
        }

        public Criteria andQuotaAllBetween(Integer value1, Integer value2) {
            addCriterion("quota_all between", value1, value2, "quotaAll");
            return (Criteria) this;
        }

        public Criteria andQuotaAllNotBetween(Integer value1, Integer value2) {
            addCriterion("quota_all not between", value1, value2, "quotaAll");
            return (Criteria) this;
        }

        public Criteria andQuotaOneIsNull() {
            addCriterion("quota_one is null");
            return (Criteria) this;
        }

        public Criteria andQuotaOneIsNotNull() {
            addCriterion("quota_one is not null");
            return (Criteria) this;
        }

        public Criteria andQuotaOneEqualTo(Integer value) {
            addCriterion("quota_one =", value, "quotaOne");
            return (Criteria) this;
        }

        public Criteria andQuotaOneNotEqualTo(Integer value) {
            addCriterion("quota_one <>", value, "quotaOne");
            return (Criteria) this;
        }

        public Criteria andQuotaOneGreaterThan(Integer value) {
            addCriterion("quota_one >", value, "quotaOne");
            return (Criteria) this;
        }

        public Criteria andQuotaOneGreaterThanOrEqualTo(Integer value) {
            addCriterion("quota_one >=", value, "quotaOne");
            return (Criteria) this;
        }

        public Criteria andQuotaOneLessThan(Integer value) {
            addCriterion("quota_one <", value, "quotaOne");
            return (Criteria) this;
        }

        public Criteria andQuotaOneLessThanOrEqualTo(Integer value) {
            addCriterion("quota_one <=", value, "quotaOne");
            return (Criteria) this;
        }

        public Criteria andQuotaOneIn(List<Integer> values) {
            addCriterion("quota_one in", values, "quotaOne");
            return (Criteria) this;
        }

        public Criteria andQuotaOneNotIn(List<Integer> values) {
            addCriterion("quota_one not in", values, "quotaOne");
            return (Criteria) this;
        }

        public Criteria andQuotaOneBetween(Integer value1, Integer value2) {
            addCriterion("quota_one between", value1, value2, "quotaOne");
            return (Criteria) this;
        }

        public Criteria andQuotaOneNotBetween(Integer value1, Integer value2) {
            addCriterion("quota_one not between", value1, value2, "quotaOne");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoIsNull() {
            addCriterion("quota_two is null");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoIsNotNull() {
            addCriterion("quota_two is not null");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoEqualTo(Integer value) {
            addCriterion("quota_two =", value, "quotaTwo");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoNotEqualTo(Integer value) {
            addCriterion("quota_two <>", value, "quotaTwo");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoGreaterThan(Integer value) {
            addCriterion("quota_two >", value, "quotaTwo");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoGreaterThanOrEqualTo(Integer value) {
            addCriterion("quota_two >=", value, "quotaTwo");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoLessThan(Integer value) {
            addCriterion("quota_two <", value, "quotaTwo");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoLessThanOrEqualTo(Integer value) {
            addCriterion("quota_two <=", value, "quotaTwo");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoIn(List<Integer> values) {
            addCriterion("quota_two in", values, "quotaTwo");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoNotIn(List<Integer> values) {
            addCriterion("quota_two not in", values, "quotaTwo");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoBetween(Integer value1, Integer value2) {
            addCriterion("quota_two between", value1, value2, "quotaTwo");
            return (Criteria) this;
        }

        public Criteria andQuotaTwoNotBetween(Integer value1, Integer value2) {
            addCriterion("quota_two not between", value1, value2, "quotaTwo");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeIsNull() {
            addCriterion("quota_three is null");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeIsNotNull() {
            addCriterion("quota_three is not null");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeEqualTo(Integer value) {
            addCriterion("quota_three =", value, "quotaThree");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeNotEqualTo(Integer value) {
            addCriterion("quota_three <>", value, "quotaThree");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeGreaterThan(Integer value) {
            addCriterion("quota_three >", value, "quotaThree");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeGreaterThanOrEqualTo(Integer value) {
            addCriterion("quota_three >=", value, "quotaThree");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeLessThan(Integer value) {
            addCriterion("quota_three <", value, "quotaThree");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeLessThanOrEqualTo(Integer value) {
            addCriterion("quota_three <=", value, "quotaThree");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeIn(List<Integer> values) {
            addCriterion("quota_three in", values, "quotaThree");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeNotIn(List<Integer> values) {
            addCriterion("quota_three not in", values, "quotaThree");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeBetween(Integer value1, Integer value2) {
            addCriterion("quota_three between", value1, value2, "quotaThree");
            return (Criteria) this;
        }

        public Criteria andQuotaThreeNotBetween(Integer value1, Integer value2) {
            addCriterion("quota_three not between", value1, value2, "quotaThree");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table draw_activity
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}