package com.yuyuedao.yydwechat.entity;

public class PosterQuestionDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_question_details.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_question_details.poster_question
     *
     * @mbg.generated
     */
    private String posterQuestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_question_details.poster_answer1
     *
     * @mbg.generated
     */
    private String posterAnswer1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_question_details.question_sort
     *
     * @mbg.generated
     */
    private Integer questionSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_question_details.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_question_details.poster_answer2
     *
     * @mbg.generated
     */
    private String posterAnswer2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_question_details.poster_answer3
     *
     * @mbg.generated
     */
    private String posterAnswer3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_question_details.poster_answer4
     *
     * @mbg.generated
     */
    private String posterAnswer4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_question_details.sid
     *
     * @return the value of poster_question_details.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_question_details.sid
     *
     * @param sid the value for poster_question_details.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_question_details.poster_question
     *
     * @return the value of poster_question_details.poster_question
     *
     * @mbg.generated
     */
    public String getPosterQuestion() {
        return posterQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_question_details.poster_question
     *
     * @param posterQuestion the value for poster_question_details.poster_question
     *
     * @mbg.generated
     */
    public void setPosterQuestion(String posterQuestion) {
        this.posterQuestion = posterQuestion == null ? null : posterQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_question_details.poster_answer1
     *
     * @return the value of poster_question_details.poster_answer1
     *
     * @mbg.generated
     */
    public String getPosterAnswer1() {
        return posterAnswer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_question_details.poster_answer1
     *
     * @param posterAnswer1 the value for poster_question_details.poster_answer1
     *
     * @mbg.generated
     */
    public void setPosterAnswer1(String posterAnswer1) {
        this.posterAnswer1 = posterAnswer1 == null ? null : posterAnswer1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_question_details.question_sort
     *
     * @return the value of poster_question_details.question_sort
     *
     * @mbg.generated
     */
    public Integer getQuestionSort() {
        return questionSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_question_details.question_sort
     *
     * @param questionSort the value for poster_question_details.question_sort
     *
     * @mbg.generated
     */
    public void setQuestionSort(Integer questionSort) {
        this.questionSort = questionSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_question_details.question_id
     *
     * @return the value of poster_question_details.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_question_details.question_id
     *
     * @param questionId the value for poster_question_details.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_question_details.poster_answer2
     *
     * @return the value of poster_question_details.poster_answer2
     *
     * @mbg.generated
     */
    public String getPosterAnswer2() {
        return posterAnswer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_question_details.poster_answer2
     *
     * @param posterAnswer2 the value for poster_question_details.poster_answer2
     *
     * @mbg.generated
     */
    public void setPosterAnswer2(String posterAnswer2) {
        this.posterAnswer2 = posterAnswer2 == null ? null : posterAnswer2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_question_details.poster_answer3
     *
     * @return the value of poster_question_details.poster_answer3
     *
     * @mbg.generated
     */
    public String getPosterAnswer3() {
        return posterAnswer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_question_details.poster_answer3
     *
     * @param posterAnswer3 the value for poster_question_details.poster_answer3
     *
     * @mbg.generated
     */
    public void setPosterAnswer3(String posterAnswer3) {
        this.posterAnswer3 = posterAnswer3 == null ? null : posterAnswer3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_question_details.poster_answer4
     *
     * @return the value of poster_question_details.poster_answer4
     *
     * @mbg.generated
     */
    public String getPosterAnswer4() {
        return posterAnswer4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_question_details.poster_answer4
     *
     * @param posterAnswer4 the value for poster_question_details.poster_answer4
     *
     * @mbg.generated
     */
    public void setPosterAnswer4(String posterAnswer4) {
        this.posterAnswer4 = posterAnswer4 == null ? null : posterAnswer4.trim();
    }
}