package com.yuyuedao.yydwechat.entity;

public class PosterQuestions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_questions.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_questions.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_questions.sid
     *
     * @return the value of poster_questions.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_questions.sid
     *
     * @param sid the value for poster_questions.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_questions.sname
     *
     * @return the value of poster_questions.sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_questions.sname
     *
     * @param sname the value for poster_questions.sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }
}