package com.yuyuedao.yydwechat.entity;

public class PosterActivity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_activity.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_activity.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_activity.poster_id
     *
     * @mbg.generated
     */
    private Integer posterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_activity.use_activity
     *
     * @mbg.generated
     */
    private Integer useActivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster_activity.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_activity.sid
     *
     * @return the value of poster_activity.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_activity.sid
     *
     * @param sid the value for poster_activity.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_activity.question_id
     *
     * @return the value of poster_activity.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_activity.question_id
     *
     * @param questionId the value for poster_activity.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_activity.poster_id
     *
     * @return the value of poster_activity.poster_id
     *
     * @mbg.generated
     */
    public Integer getPosterId() {
        return posterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_activity.poster_id
     *
     * @param posterId the value for poster_activity.poster_id
     *
     * @mbg.generated
     */
    public void setPosterId(Integer posterId) {
        this.posterId = posterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_activity.use_activity
     *
     * @return the value of poster_activity.use_activity
     *
     * @mbg.generated
     */
    public Integer getUseActivity() {
        return useActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_activity.use_activity
     *
     * @param useActivity the value for poster_activity.use_activity
     *
     * @mbg.generated
     */
    public void setUseActivity(Integer useActivity) {
        this.useActivity = useActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster_activity.sname
     *
     * @return the value of poster_activity.sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster_activity.sname
     *
     * @param sname the value for poster_activity.sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }
}