package com.yuyuedao.yydwechat.entity;

import java.util.Date;

public class WPFans {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_fans.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_fans.subscribe
     *
     * @mbg.generated
     */
    private Integer subscribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_fans.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_fans.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_fans.head_url
     *
     * @mbg.generated
     */
    private String headUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_fans.accountid
     *
     * @mbg.generated
     */
    private String accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_fans.subtime
     *
     * @mbg.generated
     */
    private Date subtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_fans.invate_openid
     *
     * @mbg.generated
     */
    private String invateOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_fans.activityId
     *
     * @mbg.generated
     */
    private Integer activityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_fans.sid
     *
     * @return the value of w_p_fans.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_fans.sid
     *
     * @param sid the value for w_p_fans.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_fans.subscribe
     *
     * @return the value of w_p_fans.subscribe
     *
     * @mbg.generated
     */
    public Integer getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_fans.subscribe
     *
     * @param subscribe the value for w_p_fans.subscribe
     *
     * @mbg.generated
     */
    public void setSubscribe(Integer subscribe) {
        this.subscribe = subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_fans.openid
     *
     * @return the value of w_p_fans.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_fans.openid
     *
     * @param openid the value for w_p_fans.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_fans.nickname
     *
     * @return the value of w_p_fans.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_fans.nickname
     *
     * @param nickname the value for w_p_fans.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_fans.head_url
     *
     * @return the value of w_p_fans.head_url
     *
     * @mbg.generated
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_fans.head_url
     *
     * @param headUrl the value for w_p_fans.head_url
     *
     * @mbg.generated
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_fans.accountid
     *
     * @return the value of w_p_fans.accountid
     *
     * @mbg.generated
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_fans.accountid
     *
     * @param accountid the value for w_p_fans.accountid
     *
     * @mbg.generated
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid == null ? null : accountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_fans.subtime
     *
     * @return the value of w_p_fans.subtime
     *
     * @mbg.generated
     */
    public Date getSubtime() {
        return subtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_fans.subtime
     *
     * @param subtime the value for w_p_fans.subtime
     *
     * @mbg.generated
     */
    public void setSubtime(Date subtime) {
        this.subtime = subtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_fans.invate_openid
     *
     * @return the value of w_p_fans.invate_openid
     *
     * @mbg.generated
     */
    public String getInvateOpenid() {
        return invateOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_fans.invate_openid
     *
     * @param invateOpenid the value for w_p_fans.invate_openid
     *
     * @mbg.generated
     */
    public void setInvateOpenid(String invateOpenid) {
        this.invateOpenid = invateOpenid == null ? null : invateOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_fans.activityId
     *
     * @return the value of w_p_fans.activityId
     *
     * @mbg.generated
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_fans.activityId
     *
     * @param activityid the value for w_p_fans.activityId
     *
     * @mbg.generated
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }
}