package com.yuyuedao.yydwechat.entity;

import java.util.Date;

public class WPGzhf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_gzhf.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_gzhf.accountid
     *
     * @mbg.generated
     */
    private String accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_gzhf.textmsg
     *
     * @mbg.generated
     */
    private String textmsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_gzhf.stype
     *
     * @mbg.generated
     */
    private String stype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_gzhf.newsid
     *
     * @mbg.generated
     */
    private String newsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_gzhf.imgurl
     *
     * @mbg.generated
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_gzhf.MediaId
     *
     * @mbg.generated
     */
    private String mediaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_gzhf.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_gzhf.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_gzhf.sid
     *
     * @return the value of w_p_gzhf.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_gzhf.sid
     *
     * @param sid the value for w_p_gzhf.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_gzhf.accountid
     *
     * @return the value of w_p_gzhf.accountid
     *
     * @mbg.generated
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_gzhf.accountid
     *
     * @param accountid the value for w_p_gzhf.accountid
     *
     * @mbg.generated
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid == null ? null : accountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_gzhf.textmsg
     *
     * @return the value of w_p_gzhf.textmsg
     *
     * @mbg.generated
     */
    public String getTextmsg() {
        return textmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_gzhf.textmsg
     *
     * @param textmsg the value for w_p_gzhf.textmsg
     *
     * @mbg.generated
     */
    public void setTextmsg(String textmsg) {
        this.textmsg = textmsg == null ? null : textmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_gzhf.stype
     *
     * @return the value of w_p_gzhf.stype
     *
     * @mbg.generated
     */
    public String getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_gzhf.stype
     *
     * @param stype the value for w_p_gzhf.stype
     *
     * @mbg.generated
     */
    public void setStype(String stype) {
        this.stype = stype == null ? null : stype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_gzhf.newsid
     *
     * @return the value of w_p_gzhf.newsid
     *
     * @mbg.generated
     */
    public String getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_gzhf.newsid
     *
     * @param newsid the value for w_p_gzhf.newsid
     *
     * @mbg.generated
     */
    public void setNewsid(String newsid) {
        this.newsid = newsid == null ? null : newsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_gzhf.imgurl
     *
     * @return the value of w_p_gzhf.imgurl
     *
     * @mbg.generated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_gzhf.imgurl
     *
     * @param imgurl the value for w_p_gzhf.imgurl
     *
     * @mbg.generated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_gzhf.MediaId
     *
     * @return the value of w_p_gzhf.MediaId
     *
     * @mbg.generated
     */
    public String getMediaid() {
        return mediaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_gzhf.MediaId
     *
     * @param mediaid the value for w_p_gzhf.MediaId
     *
     * @mbg.generated
     */
    public void setMediaid(String mediaid) {
        this.mediaid = mediaid == null ? null : mediaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_gzhf.type
     *
     * @return the value of w_p_gzhf.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_gzhf.type
     *
     * @param type the value for w_p_gzhf.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_gzhf.addtime
     *
     * @return the value of w_p_gzhf.addtime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_gzhf.addtime
     *
     * @param addtime the value for w_p_gzhf.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}