package com.yuyuedao.yydwechat.entity;

public class WPMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_menu.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_menu.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_menu.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_menu.menuname
     *
     * @mbg.generated
     */
    private String menuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_menu.menukey
     *
     * @mbg.generated
     */
    private String menukey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_menu.accountid
     *
     * @mbg.generated
     */
    private String accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_menu.keyid
     *
     * @mbg.generated
     */
    private String keyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_menu.urltype
     *
     * @mbg.generated
     */
    private String urltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_menu.fatherId
     *
     * @mbg.generated
     */
    private Integer fatherid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_menu.sid
     *
     * @return the value of w_p_menu.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_menu.sid
     *
     * @param sid the value for w_p_menu.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_menu.type
     *
     * @return the value of w_p_menu.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_menu.type
     *
     * @param type the value for w_p_menu.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_menu.url
     *
     * @return the value of w_p_menu.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_menu.url
     *
     * @param url the value for w_p_menu.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_menu.menuname
     *
     * @return the value of w_p_menu.menuname
     *
     * @mbg.generated
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_menu.menuname
     *
     * @param menuname the value for w_p_menu.menuname
     *
     * @mbg.generated
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_menu.menukey
     *
     * @return the value of w_p_menu.menukey
     *
     * @mbg.generated
     */
    public String getMenukey() {
        return menukey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_menu.menukey
     *
     * @param menukey the value for w_p_menu.menukey
     *
     * @mbg.generated
     */
    public void setMenukey(String menukey) {
        this.menukey = menukey == null ? null : menukey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_menu.accountid
     *
     * @return the value of w_p_menu.accountid
     *
     * @mbg.generated
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_menu.accountid
     *
     * @param accountid the value for w_p_menu.accountid
     *
     * @mbg.generated
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid == null ? null : accountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_menu.keyid
     *
     * @return the value of w_p_menu.keyid
     *
     * @mbg.generated
     */
    public String getKeyid() {
        return keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_menu.keyid
     *
     * @param keyid the value for w_p_menu.keyid
     *
     * @mbg.generated
     */
    public void setKeyid(String keyid) {
        this.keyid = keyid == null ? null : keyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_menu.urltype
     *
     * @return the value of w_p_menu.urltype
     *
     * @mbg.generated
     */
    public String getUrltype() {
        return urltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_menu.urltype
     *
     * @param urltype the value for w_p_menu.urltype
     *
     * @mbg.generated
     */
    public void setUrltype(String urltype) {
        this.urltype = urltype == null ? null : urltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_menu.fatherId
     *
     * @return the value of w_p_menu.fatherId
     *
     * @mbg.generated
     */
    public Integer getFatherid() {
        return fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_menu.fatherId
     *
     * @param fatherid the value for w_p_menu.fatherId
     *
     * @mbg.generated
     */
    public void setFatherid(Integer fatherid) {
        this.fatherid = fatherid;
    }
}