package com.yuyuedao.yydwechat.entity;

import java.util.Date;

public class WPNewsdetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_newsDetails.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_newsDetails.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_newsDetails.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_newsDetails.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_newsDetails.picUrl
     *
     * @mbg.generated
     */
    private String picurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_newsDetails.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_newsDetails.urlType
     *
     * @mbg.generated
     */
    private String urltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_newsDetails.smallPic
     *
     * @mbg.generated
     */
    private String smallpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_newsDetails.opDate
     *
     * @mbg.generated
     */
    private Date opdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_newsDetails.accountId
     *
     * @mbg.generated
     */
    private String accountid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_newsDetails.sid
     *
     * @return the value of w_p_newsDetails.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_newsDetails.sid
     *
     * @param sid the value for w_p_newsDetails.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_newsDetails.title
     *
     * @return the value of w_p_newsDetails.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_newsDetails.title
     *
     * @param title the value for w_p_newsDetails.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_newsDetails.content
     *
     * @return the value of w_p_newsDetails.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_newsDetails.content
     *
     * @param content the value for w_p_newsDetails.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_newsDetails.description
     *
     * @return the value of w_p_newsDetails.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_newsDetails.description
     *
     * @param description the value for w_p_newsDetails.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_newsDetails.picUrl
     *
     * @return the value of w_p_newsDetails.picUrl
     *
     * @mbg.generated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_newsDetails.picUrl
     *
     * @param picurl the value for w_p_newsDetails.picUrl
     *
     * @mbg.generated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_newsDetails.url
     *
     * @return the value of w_p_newsDetails.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_newsDetails.url
     *
     * @param url the value for w_p_newsDetails.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_newsDetails.urlType
     *
     * @return the value of w_p_newsDetails.urlType
     *
     * @mbg.generated
     */
    public String getUrltype() {
        return urltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_newsDetails.urlType
     *
     * @param urltype the value for w_p_newsDetails.urlType
     *
     * @mbg.generated
     */
    public void setUrltype(String urltype) {
        this.urltype = urltype == null ? null : urltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_newsDetails.smallPic
     *
     * @return the value of w_p_newsDetails.smallPic
     *
     * @mbg.generated
     */
    public String getSmallpic() {
        return smallpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_newsDetails.smallPic
     *
     * @param smallpic the value for w_p_newsDetails.smallPic
     *
     * @mbg.generated
     */
    public void setSmallpic(String smallpic) {
        this.smallpic = smallpic == null ? null : smallpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_newsDetails.opDate
     *
     * @return the value of w_p_newsDetails.opDate
     *
     * @mbg.generated
     */
    public Date getOpdate() {
        return opdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_newsDetails.opDate
     *
     * @param opdate the value for w_p_newsDetails.opDate
     *
     * @mbg.generated
     */
    public void setOpdate(Date opdate) {
        this.opdate = opdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_newsDetails.accountId
     *
     * @return the value of w_p_newsDetails.accountId
     *
     * @mbg.generated
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_newsDetails.accountId
     *
     * @param accountid the value for w_p_newsDetails.accountId
     *
     * @mbg.generated
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid == null ? null : accountid.trim();
    }
}