package com.yuyuedao.yydwechat.mapper.generator;

import com.yuyuedao.yydwechat.entity.AToken;
import com.yuyuedao.yydwechat.entity.ATokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ATokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    long countByExample(ATokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    int deleteByExample(ATokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    int insert(AToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    int insertSelective(AToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    List<AToken> selectByExample(ATokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    AToken selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AToken record, @Param("example") ATokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AToken record, @Param("example") ATokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AToken record);
}