package com.yuyuedao.yydwechat.mapper.generator;

import com.yuyuedao.yydwechat.entity.DrawActivity;
import com.yuyuedao.yydwechat.entity.DrawActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrawActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    long countByExample(DrawActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    int deleteByExample(DrawActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    int insert(DrawActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    int insertSelective(DrawActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    List<DrawActivity> selectByExample(DrawActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    DrawActivity selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DrawActivity record, @Param("example") DrawActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DrawActivity record, @Param("example") DrawActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DrawActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DrawActivity record);
}