package com.yuyuedao.yydwechat.mapper.generator;

import com.yuyuedao.yydwechat.entity.DrawWinning;
import com.yuyuedao.yydwechat.entity.DrawWinningExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrawWinningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_winning
     *
     * @mbg.generated
     */
    long countByExample(DrawWinningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_winning
     *
     * @mbg.generated
     */
    int deleteByExample(DrawWinningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_winning
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_winning
     *
     * @mbg.generated
     */
    int insert(DrawWinning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_winning
     *
     * @mbg.generated
     */
    int insertSelective(DrawWinning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_winning
     *
     * @mbg.generated
     */
    List<DrawWinning> selectByExample(DrawWinningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_winning
     *
     * @mbg.generated
     */
    DrawWinning selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_winning
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DrawWinning record, @Param("example") DrawWinningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_winning
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DrawWinning record, @Param("example") DrawWinningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_winning
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DrawWinning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table draw_winning
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DrawWinning record);
}