package com.yuyuedao.yydwechat.mapper.generator;

import com.yuyuedao.yydwechat.entity.PosterQuestions;
import com.yuyuedao.yydwechat.entity.PosterQuestionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PosterQuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_questions
     *
     * @mbg.generated
     */
    long countByExample(PosterQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_questions
     *
     * @mbg.generated
     */
    int deleteByExample(PosterQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_questions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_questions
     *
     * @mbg.generated
     */
    int insert(PosterQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_questions
     *
     * @mbg.generated
     */
    int insertSelective(PosterQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_questions
     *
     * @mbg.generated
     */
    List<PosterQuestions> selectByExample(PosterQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_questions
     *
     * @mbg.generated
     */
    PosterQuestions selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_questions
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PosterQuestions record, @Param("example") PosterQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_questions
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PosterQuestions record, @Param("example") PosterQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PosterQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PosterQuestions record);
}