package com.yuyuedao.yydwechat.mapper.generator;

import com.yuyuedao.yydwechat.entity.PosterActivity;
import com.yuyuedao.yydwechat.entity.PosterActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PosterActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_activity
     *
     * @mbg.generated
     */
    long countByExample(PosterActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_activity
     *
     * @mbg.generated
     */
    int deleteByExample(PosterActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_activity
     *
     * @mbg.generated
     */
    int insert(PosterActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_activity
     *
     * @mbg.generated
     */
    int insertSelective(PosterActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_activity
     *
     * @mbg.generated
     */
    List<PosterActivity> selectByExample(PosterActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_activity
     *
     * @mbg.generated
     */
    PosterActivity selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_activity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PosterActivity record, @Param("example") PosterActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_activity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PosterActivity record, @Param("example") PosterActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PosterActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PosterActivity record);
}