package com.yuyuedao.yydwechat.mapper.generator;

import com.yuyuedao.yydwechat.entity.PosterQuestionDetails;
import com.yuyuedao.yydwechat.entity.PosterQuestionDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PosterQuestionDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_question_details
     *
     * @mbg.generated
     */
    long countByExample(PosterQuestionDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_question_details
     *
     * @mbg.generated
     */
    int deleteByExample(PosterQuestionDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_question_details
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_question_details
     *
     * @mbg.generated
     */
    int insert(PosterQuestionDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_question_details
     *
     * @mbg.generated
     */
    int insertSelective(PosterQuestionDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_question_details
     *
     * @mbg.generated
     */
    List<PosterQuestionDetails> selectByExample(PosterQuestionDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_question_details
     *
     * @mbg.generated
     */
    PosterQuestionDetails selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_question_details
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PosterQuestionDetails record, @Param("example") PosterQuestionDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_question_details
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PosterQuestionDetails record, @Param("example") PosterQuestionDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_question_details
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PosterQuestionDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poster_question_details
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PosterQuestionDetails record);
}