package com.yuyuedao.yydwechat.mapper.generator;

import com.yuyuedao.yydwechat.entity.TextMsg;
import com.yuyuedao.yydwechat.entity.TextMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TextMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textMsg
     *
     * @mbg.generated
     */
    long countByExample(TextMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textMsg
     *
     * @mbg.generated
     */
    int deleteByExample(TextMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textMsg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textMsg
     *
     * @mbg.generated
     */
    int insert(TextMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textMsg
     *
     * @mbg.generated
     */
    int insertSelective(TextMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textMsg
     *
     * @mbg.generated
     */
    List<TextMsg> selectByExample(TextMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textMsg
     *
     * @mbg.generated
     */
    TextMsg selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textMsg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TextMsg record, @Param("example") TextMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textMsg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TextMsg record, @Param("example") TextMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textMsg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TextMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table textMsg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TextMsg record);
}