package com.yuyuedao.yydwechat.mapper.generator;

import com.yuyuedao.yydwechat.entity.WPGzhf;
import com.yuyuedao.yydwechat.entity.WPGzhfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WPGzhfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_gzhf
     *
     * @mbg.generated
     */
    long countByExample(WPGzhfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_gzhf
     *
     * @mbg.generated
     */
    int deleteByExample(WPGzhfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_gzhf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_gzhf
     *
     * @mbg.generated
     */
    int insert(WPGzhf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_gzhf
     *
     * @mbg.generated
     */
    int insertSelective(WPGzhf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_gzhf
     *
     * @mbg.generated
     */
    List<WPGzhf> selectByExample(WPGzhfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_gzhf
     *
     * @mbg.generated
     */
    WPGzhf selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_gzhf
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WPGzhf record, @Param("example") WPGzhfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_gzhf
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WPGzhf record, @Param("example") WPGzhfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_gzhf
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WPGzhf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_gzhf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WPGzhf record);
}