package com.yuyuedao.yydwechat.mapper.generator;

import com.yuyuedao.yydwechat.entity.WPMenu;
import com.yuyuedao.yydwechat.entity.WPMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WPMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_menu
     *
     * @mbg.generated
     */
    long countByExample(WPMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_menu
     *
     * @mbg.generated
     */
    int deleteByExample(WPMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_menu
     *
     * @mbg.generated
     */
    int insert(WPMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_menu
     *
     * @mbg.generated
     */
    int insertSelective(WPMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_menu
     *
     * @mbg.generated
     */
    List<WPMenu> selectByExample(WPMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_menu
     *
     * @mbg.generated
     */
    WPMenu selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WPMenu record, @Param("example") WPMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WPMenu record, @Param("example") WPMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WPMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WPMenu record);
}